### ISSUE TITLE
MRFC522 hexadecimal input

### ISSUE THREAD

**Issue by sohailahmadsgd** [shivamvku/flakrfid#1]
Hi
I am working on a project and want to enter Hexadecimal values for input data rather than ACII.
I am really new to RPi and also to Python. I dont know where to ask and how to get help.
Can you help me

**Comment by shivamvku** [comment]
input data ---- > If u r giving input the use hex(input()) assign to a var , or binascii.unhexlify() for  convert hexadecimal digits to bytes. Mostly use input fuction if u are using the python3.

**Comment by sohailahmadsgd** [comment]
Thanks a lot ... I have solved this issue
